// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: titan/reward/query.proto

package reward

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName                 = "/titan.reward.Query/Params"
	Query_ShowExtractedVoucher_FullMethodName   = "/titan.reward.Query/ShowExtractedVoucher"
	Query_ShowUnextractedVoucher_FullMethodName = "/titan.reward.Query/ShowUnextractedVoucher"
	Query_ListExtractedVoucher_FullMethodName   = "/titan.reward.Query/ListExtractedVoucher"
	Query_ListUnextractedVoucher_FullMethodName = "/titan.reward.Query/ListUnextractedVoucher"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ShowExtractedVoucher items.
	ShowExtractedVoucher(ctx context.Context, in *QueryShowExtractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowExtractedVoucherResponse, error)
	// Queries a list of ShowUnextractedVoucher items.
	ShowUnextractedVoucher(ctx context.Context, in *QueryShowUnextractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowUnextractedVoucherResponse, error)
	// Queries a list of ListExtractedVoucher items.
	ListExtractedVoucher(ctx context.Context, in *QueryListExtractedVoucherRequest, opts ...grpc.CallOption) (*QueryListExtractedVoucherResponse, error)
	// Queries a list of ListUnextractedVoucher items.
	ListUnextractedVoucher(ctx context.Context, in *QueryListUnextractedVoucherRequest, opts ...grpc.CallOption) (*QueryListUnextractedVoucherResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowExtractedVoucher(ctx context.Context, in *QueryShowExtractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowExtractedVoucherResponse, error) {
	out := new(QueryShowExtractedVoucherResponse)
	err := c.cc.Invoke(ctx, Query_ShowExtractedVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowUnextractedVoucher(ctx context.Context, in *QueryShowUnextractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowUnextractedVoucherResponse, error) {
	out := new(QueryShowUnextractedVoucherResponse)
	err := c.cc.Invoke(ctx, Query_ShowUnextractedVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListExtractedVoucher(ctx context.Context, in *QueryListExtractedVoucherRequest, opts ...grpc.CallOption) (*QueryListExtractedVoucherResponse, error) {
	out := new(QueryListExtractedVoucherResponse)
	err := c.cc.Invoke(ctx, Query_ListExtractedVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListUnextractedVoucher(ctx context.Context, in *QueryListUnextractedVoucherRequest, opts ...grpc.CallOption) (*QueryListUnextractedVoucherResponse, error) {
	out := new(QueryListUnextractedVoucherResponse)
	err := c.cc.Invoke(ctx, Query_ListUnextractedVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ShowExtractedVoucher items.
	ShowExtractedVoucher(context.Context, *QueryShowExtractedVoucherRequest) (*QueryShowExtractedVoucherResponse, error)
	// Queries a list of ShowUnextractedVoucher items.
	ShowUnextractedVoucher(context.Context, *QueryShowUnextractedVoucherRequest) (*QueryShowUnextractedVoucherResponse, error)
	// Queries a list of ListExtractedVoucher items.
	ListExtractedVoucher(context.Context, *QueryListExtractedVoucherRequest) (*QueryListExtractedVoucherResponse, error)
	// Queries a list of ListUnextractedVoucher items.
	ListUnextractedVoucher(context.Context, *QueryListUnextractedVoucherRequest) (*QueryListUnextractedVoucherResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) ShowExtractedVoucher(context.Context, *QueryShowExtractedVoucherRequest) (*QueryShowExtractedVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowExtractedVoucher not implemented")
}
func (UnimplementedQueryServer) ShowUnextractedVoucher(context.Context, *QueryShowUnextractedVoucherRequest) (*QueryShowUnextractedVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowUnextractedVoucher not implemented")
}
func (UnimplementedQueryServer) ListExtractedVoucher(context.Context, *QueryListExtractedVoucherRequest) (*QueryListExtractedVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExtractedVoucher not implemented")
}
func (UnimplementedQueryServer) ListUnextractedVoucher(context.Context, *QueryListUnextractedVoucherRequest) (*QueryListUnextractedVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUnextractedVoucher not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowExtractedVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowExtractedVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowExtractedVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ShowExtractedVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowExtractedVoucher(ctx, req.(*QueryShowExtractedVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowUnextractedVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowUnextractedVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowUnextractedVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ShowUnextractedVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowUnextractedVoucher(ctx, req.(*QueryShowUnextractedVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListExtractedVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListExtractedVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListExtractedVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListExtractedVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListExtractedVoucher(ctx, req.(*QueryListExtractedVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListUnextractedVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListUnextractedVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListUnextractedVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListUnextractedVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListUnextractedVoucher(ctx, req.(*QueryListUnextractedVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "titan.reward.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowExtractedVoucher",
			Handler:    _Query_ShowExtractedVoucher_Handler,
		},
		{
			MethodName: "ShowUnextractedVoucher",
			Handler:    _Query_ShowUnextractedVoucher_Handler,
		},
		{
			MethodName: "ListExtractedVoucher",
			Handler:    _Query_ListExtractedVoucher_Handler,
		},
		{
			MethodName: "ListUnextractedVoucher",
			Handler:    _Query_ListUnextractedVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "titan/reward/query.proto",
}
