// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: titan/reward/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a572971f82b2a6, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a572971f82b2a6, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryShowExtractedVoucherRequest struct {
	Beneficiary string `protobuf:"bytes,1,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
}

func (m *QueryShowExtractedVoucherRequest) Reset()         { *m = QueryShowExtractedVoucherRequest{} }
func (m *QueryShowExtractedVoucherRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowExtractedVoucherRequest) ProtoMessage()    {}
func (*QueryShowExtractedVoucherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a572971f82b2a6, []int{2}
}
func (m *QueryShowExtractedVoucherRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowExtractedVoucherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowExtractedVoucherRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowExtractedVoucherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowExtractedVoucherRequest.Merge(m, src)
}
func (m *QueryShowExtractedVoucherRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowExtractedVoucherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowExtractedVoucherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowExtractedVoucherRequest proto.InternalMessageInfo

func (m *QueryShowExtractedVoucherRequest) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

type QueryShowExtractedVoucherResponse struct {
	Voucher *Voucher `protobuf:"bytes,1,opt,name=voucher,proto3" json:"voucher,omitempty"`
}

func (m *QueryShowExtractedVoucherResponse) Reset()         { *m = QueryShowExtractedVoucherResponse{} }
func (m *QueryShowExtractedVoucherResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowExtractedVoucherResponse) ProtoMessage()    {}
func (*QueryShowExtractedVoucherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a572971f82b2a6, []int{3}
}
func (m *QueryShowExtractedVoucherResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowExtractedVoucherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowExtractedVoucherResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowExtractedVoucherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowExtractedVoucherResponse.Merge(m, src)
}
func (m *QueryShowExtractedVoucherResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowExtractedVoucherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowExtractedVoucherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowExtractedVoucherResponse proto.InternalMessageInfo

func (m *QueryShowExtractedVoucherResponse) GetVoucher() *Voucher {
	if m != nil {
		return m.Voucher
	}
	return nil
}

type QueryShowUnextractedVoucherRequest struct {
	Beneficiary string `protobuf:"bytes,1,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
}

func (m *QueryShowUnextractedVoucherRequest) Reset()         { *m = QueryShowUnextractedVoucherRequest{} }
func (m *QueryShowUnextractedVoucherRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowUnextractedVoucherRequest) ProtoMessage()    {}
func (*QueryShowUnextractedVoucherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a572971f82b2a6, []int{4}
}
func (m *QueryShowUnextractedVoucherRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowUnextractedVoucherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowUnextractedVoucherRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowUnextractedVoucherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowUnextractedVoucherRequest.Merge(m, src)
}
func (m *QueryShowUnextractedVoucherRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowUnextractedVoucherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowUnextractedVoucherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowUnextractedVoucherRequest proto.InternalMessageInfo

func (m *QueryShowUnextractedVoucherRequest) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

type QueryShowUnextractedVoucherResponse struct {
	Voucher *Voucher `protobuf:"bytes,1,opt,name=voucher,proto3" json:"voucher,omitempty"`
}

func (m *QueryShowUnextractedVoucherResponse) Reset()         { *m = QueryShowUnextractedVoucherResponse{} }
func (m *QueryShowUnextractedVoucherResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowUnextractedVoucherResponse) ProtoMessage()    {}
func (*QueryShowUnextractedVoucherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a572971f82b2a6, []int{5}
}
func (m *QueryShowUnextractedVoucherResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowUnextractedVoucherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowUnextractedVoucherResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowUnextractedVoucherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowUnextractedVoucherResponse.Merge(m, src)
}
func (m *QueryShowUnextractedVoucherResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowUnextractedVoucherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowUnextractedVoucherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowUnextractedVoucherResponse proto.InternalMessageInfo

func (m *QueryShowUnextractedVoucherResponse) GetVoucher() *Voucher {
	if m != nil {
		return m.Voucher
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "titan.reward.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "titan.reward.QueryParamsResponse")
	proto.RegisterType((*QueryShowExtractedVoucherRequest)(nil), "titan.reward.QueryShowExtractedVoucherRequest")
	proto.RegisterType((*QueryShowExtractedVoucherResponse)(nil), "titan.reward.QueryShowExtractedVoucherResponse")
	proto.RegisterType((*QueryShowUnextractedVoucherRequest)(nil), "titan.reward.QueryShowUnextractedVoucherRequest")
	proto.RegisterType((*QueryShowUnextractedVoucherResponse)(nil), "titan.reward.QueryShowUnextractedVoucherResponse")
}

func init() { proto.RegisterFile("titan/reward/query.proto", fileDescriptor_96a572971f82b2a6) }

var fileDescriptor_96a572971f82b2a6 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x33, 0x8a, 0x95, 0x9d, 0xf5, 0xe2, 0x18, 0x97, 0x35, 0x2c, 0x31, 0x1b, 0x2f, 0xb2,
	0x87, 0x8c, 0xad, 0x8b, 0x82, 0x78, 0x5a, 0xd4, 0xa3, 0x68, 0xd5, 0x3d, 0x78, 0x59, 0x26, 0xd9,
	0x31, 0x0d, 0xda, 0x99, 0xec, 0xcc, 0x64, 0xdb, 0x22, 0x5e, 0xfc, 0x04, 0x82, 0x5f, 0xc2, 0xa3,
	0xe0, 0xd1, 0x2f, 0xd0, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0x56, 0xd0, 0x8f, 0x21, 0x9d, 0x99, 0x94,
	0x06, 0xd3, 0xa8, 0xbd, 0x84, 0xe1, 0xbd, 0xff, 0xfb, 0xbf, 0xdf, 0xbc, 0x97, 0x81, 0xdb, 0x2a,
	0x53, 0x84, 0x61, 0x41, 0x07, 0x44, 0x1c, 0xe3, 0x93, 0x82, 0x8a, 0x51, 0x94, 0x0b, 0xae, 0x38,
	0xba, 0xa0, 0x33, 0x91, 0xc9, 0x78, 0x17, 0x49, 0x3f, 0x63, 0x1c, 0xeb, 0xaf, 0x11, 0x78, 0x6e,
	0xca, 0x53, 0xae, 0x8f, 0x78, 0x7e, 0xb2, 0xd1, 0x9d, 0x94, 0xf3, 0xf4, 0x15, 0xc5, 0x24, 0xcf,
	0x30, 0x61, 0x8c, 0x2b, 0xa2, 0x32, 0xce, 0xa4, 0xcd, 0xee, 0x25, 0x5c, 0xf6, 0xb9, 0xc4, 0x31,
	0x91, 0xd4, 0x74, 0xc3, 0xa7, 0xed, 0x98, 0x2a, 0xd2, 0xc6, 0x39, 0x49, 0x33, 0xa6, 0xc5, 0x56,
	0x7b, 0xa5, 0x82, 0x96, 0x13, 0x41, 0xfa, 0xa5, 0x8d, 0x57, 0x49, 0x9d, 0xf2, 0x22, 0xe9, 0x51,
	0x61, 0x72, 0xa1, 0x0b, 0xd1, 0xe3, 0xb9, 0xf1, 0x23, 0x5d, 0xd0, 0xa5, 0x27, 0x05, 0x95, 0x2a,
	0x7c, 0x08, 0x2f, 0x55, 0xa2, 0x32, 0xe7, 0x4c, 0x52, 0x74, 0x1b, 0xb6, 0x8c, 0xf1, 0x36, 0x08,
	0xc0, 0xf5, 0xcd, 0x8e, 0x1b, 0x2d, 0xdf, 0x3a, 0x32, 0xea, 0x83, 0x8d, 0xf1, 0xb7, 0xab, 0xce,
	0x87, 0x9f, 0x1f, 0xf7, 0x40, 0xd7, 0xca, 0xc3, 0x7b, 0x30, 0xd0, 0x7e, 0x4f, 0x7a, 0x7c, 0x70,
	0x7f, 0xa8, 0x04, 0x49, 0x14, 0x3d, 0x3e, 0x34, 0x20, 0xb6, 0x27, 0x0a, 0xe0, 0x66, 0x4c, 0x19,
	0x7d, 0x91, 0x25, 0x19, 0x11, 0x23, 0xdd, 0x61, 0xa3, 0xbb, 0x1c, 0x0a, 0x9f, 0xc2, 0xdd, 0x06,
	0x17, 0xcb, 0x88, 0xe1, 0x79, 0x7b, 0x43, 0x0b, 0x79, 0xb9, 0x0a, 0x59, 0xea, 0x4b, 0x55, 0xf8,
	0x00, 0x86, 0x0b, 0xd7, 0x67, 0x8c, 0xae, 0x4d, 0x77, 0x08, 0xaf, 0x35, 0xfa, 0xac, 0xc9, 0xd7,
	0xf9, 0x75, 0x16, 0x9e, 0xd3, 0xc6, 0xe8, 0x25, 0x6c, 0x99, 0x11, 0xa3, 0xa0, 0x5a, 0xf3, 0xe7,
	0x06, 0xbd, 0xdd, 0x06, 0x85, 0x21, 0x09, 0x77, 0xde, 0x7e, 0xf9, 0xf1, 0xfe, 0xcc, 0x16, 0x72,
	0x71, 0xcd, 0xaf, 0x83, 0x3e, 0x01, 0xe8, 0xd6, 0x0d, 0x1a, 0x45, 0x35, 0xce, 0x0d, 0x7b, 0xf5,
	0xf0, 0x3f, 0xeb, 0x2d, 0xd7, 0x1d, 0xcd, 0xb5, 0x8f, 0x3a, 0x55, 0x2e, 0xd9, 0xe3, 0x83, 0xa3,
	0xc5, 0x58, 0x8f, 0xec, 0x78, 0xf0, 0xeb, 0xa5, 0x1d, 0xbc, 0x41, 0x9f, 0x01, 0xdc, 0xaa, 0x5f,
	0x00, 0xba, 0xb1, 0x82, 0x63, 0xe5, 0xce, 0xbd, 0xf6, 0x7f, 0x54, 0x58, 0xf6, 0xbb, 0x9a, 0xfd,
	0x16, 0xda, 0xaf, 0x61, 0x2f, 0xd8, 0x5f, 0xe8, 0x0f, 0xa2, 0xf1, 0xd4, 0x07, 0x93, 0xa9, 0x0f,
	0xbe, 0x4f, 0x7d, 0xf0, 0x6e, 0xe6, 0x3b, 0x93, 0x99, 0xef, 0x7c, 0x9d, 0xf9, 0xce, 0x73, 0xd7,
	0xd8, 0x0d, 0x4b, 0x43, 0x35, 0xca, 0xa9, 0x8c, 0x5b, 0xfa, 0x0d, 0xdf, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xce, 0x95, 0x8c, 0xef, 0x97, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ShowExtractedVoucher items.
	ShowExtractedVoucher(ctx context.Context, in *QueryShowExtractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowExtractedVoucherResponse, error)
	// Queries a list of ShowUnextractedVoucher items.
	ShowUnextractedVoucher(ctx context.Context, in *QueryShowUnextractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowUnextractedVoucherResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/titan.reward.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowExtractedVoucher(ctx context.Context, in *QueryShowExtractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowExtractedVoucherResponse, error) {
	out := new(QueryShowExtractedVoucherResponse)
	err := c.cc.Invoke(ctx, "/titan.reward.Query/ShowExtractedVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowUnextractedVoucher(ctx context.Context, in *QueryShowUnextractedVoucherRequest, opts ...grpc.CallOption) (*QueryShowUnextractedVoucherResponse, error) {
	out := new(QueryShowUnextractedVoucherResponse)
	err := c.cc.Invoke(ctx, "/titan.reward.Query/ShowUnextractedVoucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ShowExtractedVoucher items.
	ShowExtractedVoucher(context.Context, *QueryShowExtractedVoucherRequest) (*QueryShowExtractedVoucherResponse, error)
	// Queries a list of ShowUnextractedVoucher items.
	ShowUnextractedVoucher(context.Context, *QueryShowUnextractedVoucherRequest) (*QueryShowUnextractedVoucherResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ShowExtractedVoucher(ctx context.Context, req *QueryShowExtractedVoucherRequest) (*QueryShowExtractedVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowExtractedVoucher not implemented")
}
func (*UnimplementedQueryServer) ShowUnextractedVoucher(ctx context.Context, req *QueryShowUnextractedVoucherRequest) (*QueryShowUnextractedVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowUnextractedVoucher not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.reward.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowExtractedVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowExtractedVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowExtractedVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.reward.Query/ShowExtractedVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowExtractedVoucher(ctx, req.(*QueryShowExtractedVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowUnextractedVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowUnextractedVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowUnextractedVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/titan.reward.Query/ShowUnextractedVoucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowUnextractedVoucher(ctx, req.(*QueryShowUnextractedVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "titan.reward.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowExtractedVoucher",
			Handler:    _Query_ShowExtractedVoucher_Handler,
		},
		{
			MethodName: "ShowUnextractedVoucher",
			Handler:    _Query_ShowUnextractedVoucher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "titan/reward/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryShowExtractedVoucherRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowExtractedVoucherRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowExtractedVoucherRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowExtractedVoucherResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowExtractedVoucherResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowExtractedVoucherResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Voucher != nil {
		{
			size, err := m.Voucher.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowUnextractedVoucherRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowUnextractedVoucherRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowUnextractedVoucherRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowUnextractedVoucherResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowUnextractedVoucherResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowUnextractedVoucherResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Voucher != nil {
		{
			size, err := m.Voucher.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryShowExtractedVoucherRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowExtractedVoucherResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Voucher != nil {
		l = m.Voucher.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowUnextractedVoucherRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowUnextractedVoucherResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Voucher != nil {
		l = m.Voucher.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowExtractedVoucherRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowExtractedVoucherRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowExtractedVoucherRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowExtractedVoucherResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowExtractedVoucherResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowExtractedVoucherResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voucher", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Voucher == nil {
				m.Voucher = &Voucher{}
			}
			if err := m.Voucher.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowUnextractedVoucherRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowUnextractedVoucherRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowUnextractedVoucherRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowUnextractedVoucherResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowUnextractedVoucherResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowUnextractedVoucherResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voucher", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Voucher == nil {
				m.Voucher = &Voucher{}
			}
			if err := m.Voucher.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
